Algoritmo "circulo"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/03/2020
Var
r, area : real

Inicio
      escreva("Digite o valor do raio do circulo: ")
      leia (r)
      
      area <- pi * exp(r,2)
      escreva ("AREA = ",area:8:3)


Fimalgoritmo