Algoritmo "soma"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/03/2020
Var
x, y, soma: inteiro
Inicio
      escreva("Digite o valor de x: ")
      leia (x)
      escreva ("Digite o valor de y: ")
      leia (y)
      soma <- x + y
      
      escreval("SOMA = ", soma)

Fimalgoritmo