Algoritmo "tabuada"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/04/2020
Var
   n, i, t: inteiro


Inicio
      escreva("Deseja a tabuada para qual valor? ")
      leia(n)
      
      para i de 1 ate 10 faca
           t <- n * i
           escreval(n," x ",i," = ",t)
      fimpara
      

Fimalgoritmo